name: CI
on: [push]
jobs:
    lighthouseci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: yarn install
            - run: yarn build
            - run: yarn lhci
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    greenframeci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: curl https://assets.greenframe.io/install.sh | bash
            - run: greenframe update alpha
            - run: yarn install
            - run: yarn build
            - run: yarn greenframe-audit
            - run: greenframe autorun ./examples/nextWebsite.js https://nextjs.org -p alphaNext3
            - run: greenframe autorun ./examples/greenframe.js https://greenframe.io -p alphaGreenframe3
            - run: greenframe autorun ./examples/ra-demo.js https://marmelab.com/react-admin-demo -p alphaRADemo3
