name: CI
on: [push]
jobs:
    lighthouseci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: yarn install
            - run: yarn build
            - run: yarn lhci
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    greenframeci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: curl https://assets.greenframe.io/install.sh | bash
            - run: greenframe update alpha
            - run: greenframe version
